//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService_Sport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    
        public virtual int Event_Create(string sport, Nullable<System.DateTime> date, string competition)
        {
            var sportParameter = sport != null ?
                new ObjectParameter("sport", sport) :
                new ObjectParameter("sport", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var competitionParameter = competition != null ?
                new ObjectParameter("competition", competition) :
                new ObjectParameter("competition", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Event_Create", sportParameter, dateParameter, competitionParameter);
        }
    }
}
